require: rubocop-rspec

Rails:
  Enabled: true

Layout/LineLength:
  Max: 100

Layout/HashAlignment:
  Enabled: false

Layout/ArgumentAlignment:
  Enabled: false

Style/Documentation:
  Enabled: false

Style/StringLiterals:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - "spec/**/*.rb"
    - "config/**/*.rb"

RSpec/NestedGroups:
  Max: 4

AllCops:
  TargetRubyVersion: 2.6.5
  Exclude:
    - "bin/*"
    - "db/migrate/*.rb"
    - "db/schema.rb"
